- commitlint.config.js
- package.json
- yarn.lock
https://netguru.atlassian.net/browse/BN-1625
> [BN-1625] Add commitlint tool

- .release-it.json
- package.json
- yarn.lock
https://netguru.atlassian.net/browse/BN-1626
> [BN-1626] Add release-it tool

- src/predefinedComponents/AvatarHeader/AvatarHeader.js
- src/predefinedComponents/DetailsHeader/DetailsHeader.js
- src/predefinedComponents/TabbedHeader/TabbedHeader.js
- src/predefinedComponents/components/UserModal/UserModal.js
Native Driver explicitly set to false.
No performance issues found.
Issues:
https://github.com/netguru/sticky-parallax-header/issues/61
> Native Driver explicitly set to false as default

- README.md
- docs/CUSTOM.md
- example/src/constants/screenStyles.js
- example/src/screens/CardScreen/CardScreen.js
- src/StickyParallaxHeader.js
- Added example of how can nested flatlist be implemented when using StickyParallaxHeader
- Added onTopReached prop
- Added info about it to CUSTOM.md and README.md
> #113 Flatlist not scrollable on iOS

- README.md
- docs/CUSTOM.md
- examples/expo/src/screens/HomeScreen/HomeScreen.js
- examples/reactNative/src/screens/HomeScreen/HomeScreen.js
- src/StickyParallaxHeader.js
> feat: added refresh control prop

- docs/issue_template.md
Issue template preview visible below
**Title**
* **I'm submitting a ...**
* **If bug, used module version**
1.0.0
* **Platform**
* **What is the current behavior?**
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
* **If is a feature request, What is the motivation / use case for changing the behavior?**
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
> feat: added issue template

- src/tests/DetailsHeader.test.js
- src/tests/__snapshots__/DetailsHeader.test.js.snap
- Created a default test for DetailsHeader.js #155 
- 100% code coverage
---
**Question:** Are there specific criteria that you guys want for tests ?
> #155 Create snapshot test for DetailsHeader.js

- src/tests/AvatarHeader.test.js
- src/tests/__snapshots__/AvatarHeader.test.js.snap
Added `AvatarHeader.test.js` in Tests to make a Snapshot of `AvatarHeader` component.
> feat: AvatarHeader Snapshot in Tests

- README.md
- src/StickyParallaxHeader.js
- src/index.d.ts
I ended up needing this for a project (a user commented how the higher deceleration rate felt weird)
I believe this resolves https://github.com/netguru/sticky-parallax-header/issues/175
Hopefully this is all that's needed, but please let me know if there's anything else!
> Add deceleration rate prop

- package.json
- yarn.lock
> ci(update): updated release it dependency

- example/babel.config.js
- example/metro.config.js
Fixed example local package path
> fix: fixed example local package path

- jest/setupTests.js
- package.json
- src/StickyParallaxHeaderComponent.tsx
- src/components/ScrollableTabBar/ScrollableTabBar.tsx
- src/components/ScrollableTabView/ScrollableTabView.tsx
- src/predefinedComponents/DetailsHeader/DetailsHeader.tsx
- src/tests/__snapshots__/AvatarHeader.test.tsx.snap
- src/tests/__snapshots__/DetailsHeader.test.tsx.snap
- src/tests/__snapshots__/StickyParallaxHeader.test.tsx.snap
- fix typescript errors
- fix tests (jest setup)
Run `yarn prepush`, all commands should succeed
> fix: prepush

- example/src/navigation/AppNavigator.js
- example/src/screens/HomeScreen/HomeScreen.tsx
- example/src/screens/additionalExamples/AvatarHeaderFlatListExample.tsx
- example/src/screens/additionalExamples/AvatarHeaderScrollViewExample.tsx
- example/src/screens/additionalExamples/AvatarHeaderSectionListExample.tsx
- package.json
- src/components/IconRenderer/IconRenderer.tsx
- src/constants/screenStyles.ts
- src/hooks/useResponsiveSize.ts
- src/predefinedComponents/AvatarHeader/AvatarHeaderFlatList.tsx
- src/predefinedComponents/AvatarHeader/AvatarHeaderProps.ts
- src/predefinedComponents/AvatarHeader/AvatarHeaderScrollView.tsx
- src/predefinedComponents/AvatarHeader/AvatarHeaderSectionList.tsx
- src/predefinedComponents/AvatarHeader/components/HeaderBar.tsx
- src/predefinedComponents/AvatarHeader/components/HeaderForeground.tsx
- src/predefinedComponents/AvatarHeader/useAvatarHeader.tsx
- src/predefinedComponents/common/SharedProps.ts
- src/predefinedComponents/common/components/HeaderBackground.tsx
- src/predefinedComponents/common/components/HeaderBackgroundImage.tsx
- src/predefinedComponents/common/components/HeaderWrapper.tsx
- src/predefinedComponents/common/hooks/usePredefinedHeader.tsx
- src/predefinedComponents/common/hooks/useRTLStyles.ts
- src/predefinedComponents/common/utils/scrollPosition.ts
- src/primitiveComponents/StickyHeaderProps.ts
- src/primitiveComponents/useStickyHeaderScrollProps.ts
- yarn.lock
- add AvatarHeader components
- add useStickyHeaderScrollProps used to handle snap-effect props
- add usePredefinedHeader used to handle header props
https://user-images.githubusercontent.com/25980166/165761933-31ccb20c-55e8-4e2f-9d1f-1197e65ca264.mp4
> feat: new api - AvatarHeader

- example/src/navigation/AppNavigator.js
- example/src/screens/HomeScreen/HomeScreen.tsx
- example/src/screens/additionalExamples/DetailsHeaderFlatListExample.tsx
- example/src/screens/additionalExamples/DetailsHeaderScrollViewExample.tsx
- example/src/screens/additionalExamples/DetailsHeaderSectionListExample.tsx
- src/predefinedComponents/DetailsHeader/DetailsHeaderFlatList.tsx
- src/predefinedComponents/DetailsHeader/DetailsHeaderProps.ts
- src/predefinedComponents/DetailsHeader/DetailsHeaderScrollView.tsx
- src/predefinedComponents/DetailsHeader/DetailsHeaderSectionList.tsx
- src/predefinedComponents/DetailsHeader/components/HeaderBar.tsx
- src/predefinedComponents/DetailsHeader/components/HeaderForeground.tsx
- src/predefinedComponents/DetailsHeader/useDetailsHeader.tsx
- add DetailsHeader components
https://user-images.githubusercontent.com/25980166/167657379-8d3fb133-d4cd-47b1-91d4-10feb1b0ad17.mp4
> feat: new api - DetailsHeader

- example/src/assets/data/tabbedSections.ts
- example/src/components/predefinedComponents/TabbedSectionHeader.tsx
- example/src/components/predefinedComponents/TabbedSectionItem.tsx
- example/src/navigation/AppNavigator.js
- example/src/screens/HomeScreen/HomeScreen.tsx
- example/src/screens/additionalExamples/TabbedHeaderListExample.tsx
- example/src/screens/additionalExamples/TabbedHeaderPagerExample.tsx
- package.json
- src/constants/screenStyles.ts
- src/predefinedComponents/TabbedHeader/TabbedHeaderList.tsx
- src/predefinedComponents/TabbedHeader/TabbedHeaderPager.tsx
- src/predefinedComponents/TabbedHeader/TabbedHeaderProps.ts
- src/predefinedComponents/TabbedHeader/components/HeaderBar.tsx
- src/predefinedComponents/TabbedHeader/components/HeaderForeground.tsx
- src/predefinedComponents/TabbedHeader/components/Pager.tsx
- src/predefinedComponents/TabbedHeader/components/Tabs.tsx
- src/predefinedComponents/TabbedHeader/useTabbedHeader.tsx
- src/predefinedComponents/common/components/DelayedFreeze.tsx
- src/primitiveComponents/useStickyHeaderScrollProps.ts
- yarn.lock
- add TabbedHeader components
https://user-images.githubusercontent.com/25980166/167794676-b23f15c6-0bc4-4cfe-86bb-612b75f88186.mp4
> feat: new api - Tabbed Header

- bitrise.yml
> chore: bitrise setup - lint & tsc

- bitrise.yml
chore: ios bitrise ruby version
> chore: ios bitrise ruby version

- bitrise.yml
> fix: ios bitrise scheme

- bitrise.yml
> fix: bitrise cache

- package.json
> chore: release 1.0.0-rc.1

- package.json
> chore: release 1.0.0-rc.2

- package.json
- yarn.lock
fix expo snack sdk 45 crash (__reanimatedWorkletInit is not a function)
> fix: expo snack sdk 45 crash (reanimatedWorkletInit is not a function)

- package.json
This pull request resolves ???
> chore: release 1.0.0-rc.3

- bitrise.yml
fix: ios .app file not deployed to bitrise artifacts
> fix: ios .app file not deployed to bitrise artifacts

- bitrise.yml
This pull request add a workflow to build the Android application and launch Appium tests in https://app.bitrise.io/app/a83b4e4adbd2a88d with visual regression tests.
> Appium Bitrise

- bitrise.yml
- create single npm reusable workflow
- clean up npm workflows
- remove bitrise cache from lint & npm workflows (https://blog.bitrise.io/post/optimizing-your-workflows -
bitrise caching does not always improve performance)
> chore: bitrise npm reusable workflow

- CONTRIBUTING.md
- README.md
This pull request resolves ???
- Fix spelling in CONTRIBUTING (alfabetically)
- Fix code highlighting in README (`react-native-safe-area-context)
> Fix spelling and code highlighting

- src/predefinedComponents/AvatarHeader/components/HeaderBar.tsx
- src/predefinedComponents/AvatarHeader/withAvatarHeaderFlashList.tsx
- src/predefinedComponents/DetailsHeader/components/HeaderBar.tsx
- src/predefinedComponents/DetailsHeader/withDetailsHeaderFlashList.tsx
- src/predefinedComponents/TabbedHeader/components/HeaderBar.tsx
- src/predefinedComponents/TabbedHeader/withTabbedHeaderFlashList.tsx
- src/primitiveComponents/withStickyHeader.tsx
- src/primitiveComponents/withStickyHeaderFlashList.tsx
This pull request resolves #379 
Continuation of #380 
> fix(#379): crash on web with Reanimated.createAnimatedComponent
